apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ryij9ze6t-java-springboot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ryij9ze6t-java-springboot 
  name: ryij9ze6t-java-springboot
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ryij9ze6t-java-springboot
    weight: 100 
