apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ryij9ze6t-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:ec347f2898352c824d971ef70b975d262b29cfcf@sha256:74dd4894eea55c054a31ac5744c832f9e8772e9197229a36bfd425a40a659eb4
          name: container-image
